patchedDependencies:
  baseline-browser-mapping@2.10.12: patches/baseline-browser-mapping@2.10.12.patch
onlyBuiltDependencies:
  - '@prisma/cli'
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
  - esbuild
  - prisma
  - sharp
  - tesseract.js
  - unrs-resolver
